############################################################
# Ticket-Tracker – Render Blueprint
############################################################

# ── list *all* services except Postgres here ──────────────
services:
  # --- Express + Vite app ---------------------------------
  - name: ticket-tracker
    type: web
    runtime: docker            # Render builds from Dockerfile
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true

    envVars:
      # Postgres connection string →
      - key: DATABASE_URL
        fromDatabase:
          name: ticket-db       # ← matches database name below
          property: connectionString

      # S3-style variables from the blob-storage service →
      - key: S3_ENDPOINT
        fromService:
          name: ticket-blob
          type: s3
          property: endpoint

      - key: S3_ACCESS_KEY
        fromService:
          name: ticket-blob
          type: s3
          property: accessKey

      - key: S3_SECRET_KEY
        fromService:
          name: ticket-blob
          type: s3
          property: secretKey

      - key: S3_BUCKET
        value: uploads          # default bucket name in your code

      - key: PORT
        value: 5000             # Express listens here (Render sets $PORT)

  # --- S3-compatible Blob Storage -------------------------
  - name: ticket-blob
    type: s3-storage
    plan: starter               # ≈ $0 unless you store multiple GB

# ── Postgres goes in its own top-level list ───────────────
databases:
  - name: ticket-db
    plan: free
    version: 15
