############################################################
# Ticket-Tracker – Render Blueprint
############################################################

# ── list *all* services except Postgres here ──────────────
services:
  # --- Express + Vite app ---------------------------------
  - name: ticket-tracker
    type: web
    runtime: docker            # Render builds from Dockerfile
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true

    envVars:
      # Postgres connection string →
      - key: DATABASE_URL
        fromDatabase:
          name: ticket-db       # ← matches database name below
          property: connectionString

      - key: PORT
        value: 5000             # Express listens here (Render sets $PORT)

# ── Postgres goes in its own top-level list ───────────────
databases:
  - name: ticket-db
    plan: free
    version: 15
