services:
  - name: ticket-tracker
    type: web
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ticket-db
          property: connectionString
      - key: PORT
        value: "5000"

databases:
  - name: ticket-db
    plan: free
    version: "15"
